#!/bin/sh
#	Copyright(c) 2012 RubytotheRails.com
#	This is free software distributed per the MIT License at www.r2dr.com/licenses/commands
#	Copyright and License URL must be included for any distribution

WISPY_VERSION=1.1
if [[ $1 == "--version" ]]; then
	echo $WISPY_VERSION
	exit
fi
watch -n 1 cat /proc/net/wireless

